### ISSUE TITLE
Rule expected but ")" found on `:is` with nested selectors

### ISSUE THREAD

**Issue by gglnx** [merkle-open/stylelint-bem#26]
## Type of issue

* Bug report

## Environment

* Node.js v16.14.2
* Mac OS 12.4
* NPM: 8.5.0
* Using `postcss-scss` as `customSyntax`

## Expected behavior

When using a nested `:is` selector, no error should be thrown.

## Current behavior

The fellowing error is thrown:

* Rule expected but ")" found `plugin/stylelint-bem-namics`

## Steps to reproduce the behavior

Create an stylesheet with the fellowing CSS code:

```css
.u-underline:is(:focus:not(.has-invisible-focus), :hover:not([disabled])) {
  text-decoration: underline;
}
```
